USE NINEAM_CLASS;
SELECT * FROM RETAIL_ORDERS;

SELECT CATEGORY , SUM(SALES) AS TOTAL_SALES
FROM RETAIL_ORDERS
GROUP BY CATEGORY
HAVING SUM(SALES) > 100000;

SELECT CITY , SUM(SALES) AS TOTAL_SALES
FROM RETAIL_ORDERS
GROUP BY CITY
HAVING SUM(SALES) > 100000;

SELECT CITY , COUNT(ORDER_ID) AS COUNT_ORDER 
FROM RETAIL_ORDERS
GROUP BY CITY
HAVING COUNT(ORDER_ID) > 3;

SELECT CUSTOMER_ID, COUNT(CUSTOMER_ID) COUNT_CUSTOMER
FROM RETAIL_ORDERS
GROUP BY CUSTOMER_ID
HAVING COUNT( CUSTOMER_ID) > 1;

SELECT CUSTOMER_ID, SUM(SALES) TOTAL_SALES , COUNT(ORDER_ID) TOTAL_ORDERS
FROM RETAIL_ORDERS
GROUP BY CUSTOMER_ID
HAVING SUM(SALES) > 2000 AND COUNT(ORDER_ID) > 1;

SELECT SUB_CATEGORY , COUNT(QUANTITY) AS TOTAL_QUANTITY , SUM(PROFIT) AS TOTAL_PROFIT
FROM RETAIL_ORDERS
GROUP BY SUB_CATEGORY
HAVING COUNT(QUANTITY) > 3 AND SUM(PROFIT) > 0;

SELECT CATEGORY , CITY , SUM(SALES) TOTAL_SALES
FROM RETAIL_ORDERS
WHERE CITY = "HYDERABAD"
GROUP BY CATEGORY , CITY
HAVING SUM(SALES) > 50000;

SELECT CITY ,CATEGORY , SUM(PROFIT) TOTAL_PROFIT
FROM RETAIL_ORDERS
WHERE CATEGORY = "TECHNOLOGY"
GROUP BY CITY ,CATEGORY
HAVING SUM(PROFIT) > 5000;

SELECT CATEGORY, ORDER_DATE, SUM(SALES) TOTAL_SALES
FROM RETAIL_ORDERS
WHERE ORDER_DATE > '2023-02-01'
GROUP BY CATEGORY, ORDER_DATE
HAVING  SUM(SALES) > 4000;

SELECT CITY , ORDER_DATE , SUM(PROFIT) TOTAL_PROFIT
FROM RETAIL_ORDERS
WHERE ORDER_DATE BETWEEN '2023-03-01' AND '2023-04-30'
GROUP BY CITY , ORDER_DATE
HAVING SUM(PROFIT) > 4000;

SELECT CATEGORY, ORDER_DATE, SUM(SALES) TOTAL_SALES
FROM RETAIL_ORDERS
WHERE  '2023-02-01'
GROUP BY CATEGORY, ORDER_DATE
HAVING  SUM(SALES) > 4000;

SELECT CUSTOMER_ID , SUM(SALES) TOTAL_SALES
FROM RETAIL_ORDERS
GROUP BY CUSTOMER_ID
ORDER BY SUM(SALES) DESC
LIMIT 5;
