USE NINEAM_CLASS;
SELECT * FROM GLOBALSUPERSTORE;

SELECT ORDER_ID, REGION
FROM GLOBALSUPERSTORE
WHERE REGION = 'WEST';


SELECT *
FROM GLOBALSUPERSTORE
WHERE CATEGORY = 'FURNITURE';

SELECT  ORDER_ID, SALES
FROM GLOBALSUPERSTORE
WHERE SALES > 500;

SELECT ORDER_ID , CITY
FROM GLOBALSUPERSTORE
WHERE CITY = 'NEW YORK CITY';

SELECT ORDER_ID, PROFIT
FROM GLOBALSUPERSTORE
WHERE PROFIT < 0;

SELECT ORDER_ID, DISCOUNT
FROM GLOBALSUPERSTORE
WHERE DISCOUNT > 0.2;

SELECT ORDER_ID, QUANTITY
FROM GLOBALSUPERSTORE
WHERE QUANTITY BETWEEN 3 AND 7;

ALTER TABLE GLOBALSUPERSTORE RENAME COLUMN `ORDER ID` TO ORDER_ID;
ALTER TABLE GLOBALSUPERSTORE RENAME COLUMN `SHIP MODE` TO SHIP_MODE;
ALTER TABLE GLOBALSUPERSTORE RENAME COLUMN `CUSTOMER NAME` TO CUSTOMER_NAME;
ALTER TABLE GLOBALSUPERSTORE RENAME COLUMN `PRODUCT NAME` TO PRODUCT_NAME;
ALTER TABLE GLOBALSUPERSTORE RENAME COLUMN `POSTAL CODE` TO POSTAL_CODE;
ALTER TABLE GLOBALSUPERSTORE RENAME COLUMN `SUB-CATEGORY` TO SUB_CATEGORY;
ALTER TABLE GLOBALSUPERSTORE RENAME COLUMN `CUSTOMER ID` TO CUSTOMER_ID;
ALTER TABLE GLOBALSUPERSTORE RENAME COLUMN `ORDER DATE` TO ORDER_DATE;
SELECT ORDER_ID, QUANTITY
FROM GLOBALSUPERSTORE
WHERE QUANTITY BETWEEN 3 AND 7;

SELECT ORDER_ID, SHIP_MODE
FROM GLOBALSUPERSTORE
WHERE SHIP_MODE = 'SECOND CLASS';

SELECT ORDER_ID, STATE
FROM GLOBALSUPERSTORE
WHERE STATE IN ('CALIFORNIA', 'TEXAS');

SELECT ORDER_ID, CATEGORY,SALES
FROM GLOBALSUPERSTORE
WHERE CATEGORY = 'TECHNOLOGY' AND SALES > 1000;

SELECT ORDER_ID, REGION, PROFIT
FROM GLOBALSUPERSTORE
WHERE REGION = 'EAST' OR PROFIT < 0;

SELECT ORDER_ID, CUSTOMER_NAME
FROM GLOBALSUPERSTORE
WHERE CUSTOMER_NAME LIKE "A%";

SELECT ORDER_ID, PRODUCT_NAME
FROM GLOBALSUPERSTORE
WHERE PRODUCT_NAME LIKE '%CHAIR%';

SELECT ORDER_ID, POSTAL_CODE
FROM GLOBALSUPERSTORE
WHERE POSTAL_CODE IS NULL;

SELECT SUM(SALES) AS TOTAL_SALES, REGION
FROM GLOBALSUPERSTORE
GROUP BY REGION ;

SELECT SUM(PROFIT) AS TOTAL_PROFIT, CATEGORY
FROM GLOBALSUPERSTORE
GROUP BY CATEGORY; 

SELECT SUM(QUANTITY) AS TOTAL_QUANTITY, SUB_CATEGORY
 FROM GLOBALSUPERSTORE
 GROUP BY SUB_CATEGORY;
 
 SELECT COUNT(ORDER_ID) AS COUNT_ORDER , SHIP_MODE
  FROM GLOBALSUPERSTORE
  GROUP BY SHIP_MODE;
  
  SELECT AVG(SALES) AS AVG_SALES, CUSTOMER_ID
   FROM GLOBALSUPERSTORE
   GROUP BY CUSTOMER_ID;
   
   SELECT SUM(SALES) AS TOTAL_SALES , SUM(PROFIT) AS TOTAL_PROFIT, REGION , CATEGORY
     FROM GLOBALSUPERSTORE
     GROUP BY REGION , CATEGORY;
    
  SELECT AVG(DISCOUNT) AS AVG_DISCOUNT , SEGMENT
    FROM GLOBALSUPERSTORE
    GROUP BY SEGMENT;
    
    SELECT COUNT(CUSTOMER_ID) AS COUNT_CUSTOMERS , REGION
     FROM GLOBALSUPERSTORE
     GROUP BY REGION;
     SELECT MAX(SALES) AS MAX_SALES , SUB_CATEGORY
       FROM GLOBALSUPERSTORE
       GROUP BY SUB_CATEGORY;

SELECT MIN(PROFIT) AS MIN_PROFIT , CATEGORY
 FROM GLOBALSUPERSTORE
 GROUP BY CATEGORY;
 
SELECT *
FROM  GLOBALSUPERSTORE
ORDER BY SALES ;   

SELECT *
FROM  GLOBALSUPERSTORE
ORDER BY PROFIT DESC;

SELECT *
FROM  GLOBALSUPERSTORE
ORDER BY ORDER_DATE DESC;

SELECT CUSTOMER_NAME
FROM  GLOBALSUPERSTORE
ORDER BY CUSTOMER_NAME;

SELECT PRODUCT_NAME , CATEGORY
FROM  GLOBALSUPERSTORE
ORDER BY PRODUCT_NAME , CATEGORY DESC;

SELECT REGION , SALES
FROM  GLOBALSUPERSTORE
ORDER BY REGION ASC , SALES DESC;

SELECT STATE , CITY
FROM  GLOBALSUPERSTORE
ORDER BY STATE , CITY;

SELECT SHIP_MODE , ORDER_DATE
FROM  GLOBALSUPERSTORE
ORDER BY SHIP_MODE , ORDER_DATE;

SELECT SEGMENT , SALES
FROM  GLOBALSUPERSTORE
ORDER BY SEGMENT DESC, SALES ASC;

SELECT CATEGORY, PROFIT
FROM  GLOBALSUPERSTORE
ORDER BY CATEGORY , PROFIT;

 SELECT CUSTOMER_ID , SUM(SALES) AS TOTAL_SALES
 FROM  GLOBALSUPERSTORE
 GROUP BY CUSTOMER_ID
 HAVING SUM(SALES)
 ORDER BY SUM(SALES) DESC LIMIT 5;
 
 SELECT SUB_CATEGORY, COUNT(QUANTITY) AS TOTAL_QUANTITY
 FROM GLOBALSUPERSTORE
 GROUP BY SUB_CATEGORY
 HAVING  COUNT(QUANTITY) > 100 
 ORDER BY COUNT(QUANTITY)  DESC
 LIMIT 5 ;
 
 SELECT REGION , AVG(SALES) AS AVG_SALES
  FROM GLOBALSUPERSTORE 
  GROUP BY REGION
  HAVING AVG(SALES) > 300
  ORDER BY AVG(SALES) DESC;
  
  SELECT CUSTOMER_ID , SUM(PROFIT) AS TOTAL_PROFIT
   FROM GLOBALSUPERSTORE
   GROUP BY CUSTOMER_ID
   HAVING SUM(PROFIT) < 0
   ORDER BY SUM(PROFIT);
   
   SELECT CATEGORY , SUM(SALES) AS TOTAL_SALES
    FROM GLOBALSUPERSTORE
    GROUP BY CATEGORY
    HAVING SUM(SALES)>5000
    LIMIT 3;
    
    SELECT SUB_CATEGORY , SUM(PROFIT) AS TOTAL_PROFIT
      FROM GLOBALSUPERSTORE
      GROUP BY SUB_CATEGORY
      HAVING SUM(PROFIT) > 0
      ORDER BY SUM(PROFIT);
      
      SELECT CUSTOMER_ID, AVG(DISCOUNT) AS AVG_DISCOUNT
       FROM GLOBALSUPERSTORE
  GROUP BY  CUSTOMER_ID
  HAVING AVG(DISCOUNT) > 0.2;
  
  SELECT REGION , COUNT(QUANTITY) AS COUNT_QUANTITY
   FROM GLOBALSUPERSTORE
   GROUP BY REGION
   HAVING COUNT(QUANTITY) > 200
   ORDER BY COUNT(QUANTITY) DESC;
   
   SELECT CUSTOMER_ID , SUM(SALES) AS SUM_SALES
      FROM GLOBALSUPERSTORE
      GROUP BY CUSTOMER_ID
      HAVING SUM(SALES) > 3000
      ORDER BY SUM(SALES) DESC
      LIMIT 5;
      
      SELECT SUB_CATEGORY, MAX(DISCOUNT) AS MAX_DISCOUNT
      FROM GLOBALSUPERSTORE
      GROUP BY SUB_CATEGORY
      HAVING MAX(DISCOUNT) > 0.5;
      
      SELECT CUSTOMER_NAME , COUNT(ORDER_ID) AS COUNT_ORDER       
      FROM GLOBALSUPERSTORE
       GROUP BY CUSTOMER_NAME 
       HAVING COUNT(ORDER_ID) > 3 
       ORDER BY  CUSTOMER_NAME ;
       
       SELECT CATEGORY , COUNT(QUANTITY) AS COUNT_QUANTITY
       FROM GLOBALSUPERSTORE
       GROUP BY CATEGORY
       HAVING COUNT(QUANTITY) > 150
       ORDER BY COUNT(QUANTITY) DESC
       LIMIT 2;
       
       SELECT REGION ,MIN(PROFIT) AS TOTAL_PROFIT
       FROM GLOBALSUPERSTORE
       GROUP BY REGION
       HAVING MIN(PROFIT) < 1000
       ORDER BY MIN(PROFIT);
       
SELECT CUSTOMER_ID , SUM(SALES) AS SUM_SALES, PROFIT
 FROM GLOBALSUPERSTORE
 GROUP BY CUSTOMER_ID,PROFIT
 HAVING SUM(SALES) > 2000
 ORDER BY  PROFIT;
 
 SELECT SUB_CATEGORY, AVG(QUANTITY) AS AVG_QUANTITY
  FROM GLOBALSUPERSTORE
  GROUP BY SUB_CATEGORY
  HAVING AVG(QUANTITY) > 3;
  
SELECT CUSTOMER_ID , SUM(PROFIT) AS TOTAL_PROFIT  
 FROM GLOBALSUPERSTORE
 GROUP BY CUSTOMER_ID
 HAVING SUM(PROFIT) >1000
 ORDER BY CUSTOMER_ID DESC
 LIMIT 4;
 
 SELECT REGION , MAX(SALES) AS MAX_SALES
  FROM GLOBALSUPERSTORE
  GROUP BY REGION
  HAVING MAX(SALES) > 2000;
  
  SELECT SUB_CATEGORY, AVG(PROFIT) AS AVG_PROFIT
    FROM GLOBALSUPERSTORE
    GROUP BY SUB_CATEGORY
    HAVING AVG(PROFIT) < 50
    ORDER BY AVG(PROFIT);
    
    SELECT REGION , SUM(SALES) AS TOTAL_SALES
     FROM GLOBALSUPERSTORE
     GROUP BY REGION 
     HAVING SUM(SALES) > 10000
     ORDER BY SUM(SALES) DESC
     LIMIT 3;
     
     SELECT CUSTOMER_ID , MIN(PROFIT) AS MIN_PROFIT
       FROM GLOBALSUPERSTORE
       GROUP BY CUSTOMER_ID
       HAVING MIN(PROFIT) < 0;
       
SELECT CATEGORY , AVG(DISCOUNT) AS AVG_DISCOUNT
   FROM GLOBALSUPERSTORE
   GROUP BY CATEGORY
   HAVING AVG(DISCOUNT) > 0.25
   ORDER BY AVG(DISCOUNT) DESC;
   
SELECT SUB_CATEGORY , SUM(PROFIT) AS SUM_PROFIT
   FROM GLOBALSUPERSTORE
   GROUP BY SUB_CATEGORY
   HAVING SUM(PROFIT) > 500
   ORDER BY SUM(PROFIT) DESC
   LIMIT 5;
   
 SELECT CUSTOMER_ID , COUNT(QUANTITY) AS COUNT_QUANTITY
  FROM GLOBALSUPERSTORE
  GROUP BY CUSTOMER_ID
  HAVING COUNT(QUANTITY) > 50
  ORDER BY COUNT(QUANTITY);
  
SELECT REGION , MIN(DISCOUNT) AS MIN_DISCOUNT
  FROM GLOBALSUPERSTORE
  GROUP BY REGION 
  HAVING MIN(DISCOUNT) = 0;
  
SELECT CUSTOMER_ID , COUNT(QUANTITY) AS COUNT_QUANTITY
 FROM GLOBALSUPERSTORE
 GROUP BY CUSTOMER_ID 
 HAVING  COUNT(QUANTITY) > 30
 ORDER BY  COUNT(QUANTITY) DESC
 LIMIT 3;
       
  
 
       

     










