USE NINEAM_CLASS;
SELECT * FROM DATE_DATA_ORDERS;
SELECT CURDATE(),
 CURTIME(),
 NOW();
 SELECT ORDER_DATE,
       YEAR(ORDER_DATE) AS YEAR,
       MONTH(ORDER_DATE) AS MONTH,
       DAY(ORDER_DATE) AS DAY,
       MONTHNAME(ORDER_DATE) AS MONTH_NAME,
       DAYNAME(ORDER_DATE) AS DAY_NAME,
       HOUR(NOW()) AS HOUR,
       MINUTE(NOW()) AS MINUTE,
       SECOND(NOW()) AS SECOND
       FROM DATE_DATA_ORDERS;
       
       
SELECT ORDER_DATE , DATE_FORMAT(ORDER_DATE , "%a") AS SHORT_DAYNAME,
                    DATE_FORMAT(ORDER_DATE , "%b") AS SHORT_MONTHNAME,
                    DATE_FORMAT(ORDER_DATE , "%Y-%m") AS YEAR
   FROM DATE_DATA_ORDERS;            
   
   
   
   SELECT ORDER_DATE,
          DATE_ADD(ORDER_DATE , INTERVAL  5 DAY) AS ADD_5_DAYS,
           DATE_ADD(ORDER_DATE , INTERVAL  5 MONTH) AS ADD_5_MONTHS,
            DATE_ADD(ORDER_DATE , INTERVAL  5 YEAR) AS ADD_5_YEARS,
             DATE_SUB(ORDER_DATE , INTERVAL  5 DAY) AS SUB_5_DAYS
FROM DATE_DATA_ORDERS;  


 SELECT ORDER_DATE , DELIVERY_DATE,
          DATEDIFF(DELIVERY_DATE , ORDER_DATE) AS DATEDIFF,
          LAST_DAY(ORDER_DATE),
          STR_TO_DATE("28-01-2024" , "%d-%m- %Y")
     FROM DATE_DATA_ORDERS;  
     
   SELECT ORDER_DATE , DELIVERY_DATE,
          DATEDIFF(DELIVERY_DATE , ORDER_DATE) AS DATEDIFF,
          LAST_DAY(ORDER_DATE),
          STR_TO_DATE("28-01-2024" , "%d-%m- %Y")
       FROM DATE_DATA_ORDERS;
       
       SELECT MONTHNAME(ORDER_DATE) AS MONTH_NAME,
       SUM(SALES) AS TOTAL_SALES
       FROM DATE_DATA_ORDERS
       GROUP BY MONTH_NAME;
       
       SELECT YEAR(ORDER_DATE) AS YEAR,
        SUM(SALES) AS TOTAL_SALES
         FROM DATE_DATA_ORDERS
         GROUP BY YEAR;
         
         SELECT ORDER_DATE , SALES ,
         DAYNAME(ORDER_DATE),
         DAYOFWEEK(ORDER_DATE)
          FROM DATE_DATA_ORDERS
          WHERE DAYOFWEEK(ORDER_DATE) IN(1,7)
          ORDER BY DAYOFWEEK(ORDER_DATE);
          
          