SELECT *
FROM RETAIL_ORDERS;
SELECT CATEGORY, SUB_CATEGORY, PRODUCT_NAME
FROM RETAIL_ORDERS;

SELECT CUSTOMER_NAME,CITY
FROM RETAIL_ORDERS
WHERE CITY="HYDERABAD";


SELECT CUSTOMER_NAME,CITY
FROM RETAIL_ORDERS
WHERE CITY !="HYDERABAD";

SELECT CUSTOMER_NAME,SALES
FROM RETAIL_ORDERS
WHERE SALES > 50000;

SELECT CUSTOMER_NAME,SALES
FROM RETAIL_ORDERS
WHERE SALES < 50000;

SELECT CUSTOMER_NAME,CITY,CATEGORY
FROM RETAIL_ORDERS
WHERE CITY="HYDERABAD" AND CATEGORY="TECHNOLOGY";

SELECT CUSTOMER_NAME,CITY
FROM RETAIL_ORDERS
WHERE CITY="CHENNAI" OR CITY="MUMBAI" OR CITY="DELHI";

SELECT CUSTOMER_NAME,SALES
FROM RETAIL_ORDERS
WHERE SALES BETWEEN 10000 AND 50000;

SELECT CUSTOMER_NAME,ORDER_DATE
FROM RETAIL_ORDERS
WHERE ORDER_DATE BETWEEN "2023-01-05" AND "2023-03-05";

SELECT CUSTOMER_NAME,CITY
FROM RETAIL_ORDERS
WHERE CITY IN ("CHENNAI","MUMBAI","DELHI");

SELECT CUSTOMER_NAME,CITY
FROM RETAIL_ORDERS
WHERE CITY  NOT IN ("CHENNAI","MUMBAI","DELHI");

SELECT CUSTOMER_NAME
FROM RETAIL_ORDERS
WHERE CUSTOMER_NAME LIKE "%Y";

SELECT CUSTOMER_NAME
FROM RETAIL_ORDERS
WHERE CUSTOMER_NAME LIKE "%IT%";

SELECT CUSTOMER_NAME
FROM RETAIL_ORDERS
WHERE CUSTOMER_NAME LIKE "____";


SELECT SUM(SALES) AS TOTAL_SALES,
AVG(SALES) AS AVG_SALES,
MIN(SALES) AS MIN_SALES,
MAX(SALES) AS MAX_SALES,
COUNT(SALES) AS TOTAL_ORDERS
FROM RETAIL_ORDERS;

SELECT CUSTOMER_NAME, SUM(SALES) AS TOTAL_SALES
FROM RETAIL_ORDERS
GROUP BY CUSTOMER_NAME;

SELECT CITY, SUM(SALES) AS TOTAL_SALES
FROM RETAIL_ORDERS
GROUP BY CITY;

SELECT CITY,CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM RETAIL_ORDERS
GROUP BY CITY,CATEGORY
ORDER BY CITY,CATEGORY;
