CREATE DATABASE NINEAM_CLASS;
USE NINEAM_CLASS;
CREATE TABLE EMP_DETAILS
(
EMP_ID INT,
EMP_NAME VARCHAR(50),
EMP_AGE SMALLINT
);
DESC EMP_DETAILS;
ALTER TABLE EMP_DETAILS ADD COLUMN DEPARTMENT VARCHAR(30);
ALTER TABLE EMP_DETAILS ADD COLUMN 
(
POSTAL_CODE INT,
CITY_NAME VARCHAR(30)
);
ALTER TABLE EMP_DETAILS MODIFY EMP_AGE TINYINT;
ALTER TABLE EMP_DETAILS DROP COLUMN POSTAL_CODE;
DESC EMP_DETAILS;
INSERT INTO EMP_DETAILS VALUES
(1,"ROJA",20,"CSE","VIZAG");
INSERT INTO EMP_DETAILS
VALUES
(2,"LIKKI",22,"IT","VIZAG"),
(3,"TARUN",18,"FINANCE","SRIKAKULAM");
SELECT * FROM EMP_DETAILS;
-- UPDATE --
SET SQL_SAFE_UPDATES=0;
SET SQL_SAFE_UPDATES=1;
UPDATE EMP_DETAILS
SET EMP_AGE = 25
WHERE EMP_NAME="ROJA";
